BLOG/PWABlog/Controllers/admin/AdminAutorController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using PWABlog.Models.Blog.Autor;
using PWABlog.RequestModels.autor;
using PWABlog.ViewModels.Admin.autor;
// ReSharper disable All

namespace PWABlog.Controllers.admin
{
    public class AdminAutorController : Controller
    {
        private readonly AutorOrmService _autorOrmService;

        public AdminAutorController(AutorOrmService autorOrmService)
        {
            _autorOrmService = autorOrmService;
        }
        
       [Route("admin/autor/index")]
       [Route("admin/autor")]
        public IActionResult Index()
        {
            var model = new AutorIndexViewModel();
            var autores = _autorOrmService.ObterAutores();

            foreach (var autor in autores)
            {
                var author = new AutorIndex();
                author.Id = autor.Id;
                author.Nome = autor.Nome;
                model.Autores.Add(author);
            }
            
            return View(model);
        }

        [HttpGet]
        [Route("admin/autor/create")]
        public IActionResult Create()
        {
            var model = new AutorCreateViewModel();
            model.Title = "Adicionar Autor";
            return View(model);
        }

        [HttpPost]
        [Route("admin/autor/create/{id?}")]
        public IActionResult Create(AdminAutorCriarRequestModel request)
        {
            var nome = request.Nome;
            var model = new AutorIndexViewModel();
            try
            {
                _autorOrmService.AddAutor(nome);
                model.Message = "Criado com sucesso!!";
                model.Tipo = "Criar";
            }
            catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Create");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
           
        }

        [Route("admin/autor/edit/{id?}")]
        public IActionResult Edit(int id)
        {
            var author = _autorOrmService.ObterAutorPorId(id);
            var model = new AutorEditViewModel();
            model.Id = author.Id;
            model.Nome = author.Nome;
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(AdminAutorUpdateRequestModel request)
        {
            var nome = request.Nome;
            var id = request.Id;
            var model = new AutorIndexViewModel();
            try
            {
                var author = new AutorEntity{Id=id,Nome = nome};
                _autorOrmService.UpdateAutor(author);
                model.Message = "Atualizado com sucesso!!";
                model.Tipo = "Update";
            }
            catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Update");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        [Route("admin/autor/remove/{id?}")]
        public IActionResult Remove(AdminAutorDeleteRequestModel request)
        {
            var id = request.Id;
            var model = new AutorIndexViewModel();
            try
            {
                _autorOrmService.RemoveAutor(id);
                model.Message = "Deletado com sucesso!!";
                model.Tipo = "Deletar";
            }catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }

        [Route("admin/autor/view/{id?}")]
        public IActionResult Details(int id)
        {
            var model = new AutorDetailsViewModel();
            var categoria = _autorOrmService.ObterAutorPorId(id);
            model.Id = categoria.Id;
            model.Nome = categoria.Nome;
            return View(model);
        }
    }
}

BLOG/PWABlog/Controllers/admin/AdminPostagemController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.DataProtection;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using NHttp;
using Pomelo.EntityFrameworkCore.MySql.Infrastructure;
using PWABlog.Models.Blog.Autor;
using PWABlog.Models.Blog.Categoria;
using PWABlog.Models.Blog.Etiqueta;
using PWABlog.Models.Blog.Postagem;
using PWABlog.RequestModels.postagem;
using PWABlog.ViewModels.Admin.postagem;

namespace PWABlog.Controllers.admin
{
    public class AdminPostagemController : Controller
    {
        private readonly PostagemOrmService _postagemOrmService;
        private readonly AutorOrmService _autorOrmService;
        private readonly CategoriaOrmService _categoriaOrmService;
        private readonly EtiquetaOrmService _etiquetaOrmService;
        private readonly DatabaseContext _databaseContext;
        private readonly IServiceScopeFactory _serviceScopeFactory;

        public AdminPostagemController(PostagemOrmService postagemOrmService,DatabaseContext databaseContext, IServiceScopeFactory serviceScopeFactory)
        {
            _postagemOrmService = postagemOrmService;
            _databaseContext = databaseContext;
            _serviceScopeFactory = serviceScopeFactory;
        }
        
        [Route("admin/postagem/index")]
        [Route("admin/postagem")]
        public IActionResult Index()
        {
            var model = new PostagemIndexViewModel();
            var postagens = _postagemOrmService.ObterPostagens();

            foreach (var postagem in postagens)
            {
                var post = new PostagemIndex();
                post.Id = postagem.Id;
                post.Autor = postagem.Autor.Nome;
                post.Categoria = postagem.Categoria.Nome;
                post.Descricao = post.Descricao;
                post.Revisoes = postagem.Revisoes;
                post.Titulo = postagem.Titulo;
                post.PostagensEtiquetas = postagem.PostagensEtiquetas;
                post.Data = postagem.Data;
                post.Time = postagem.Time;
                model.Postagens.Add(post);
            }
            return View(model);
        }
        
        [HttpGet]
        [Route("admin/postagem/create")]
        public IActionResult Create()
        {
            var modal = new PostagemCreateViewModel();
            modal.Title = "Nova Postagem";
            var _autorOrmService = new AutorOrmService(_databaseContext);
            var autores = _autorOrmService.ObterAutores();
            
            var _categoriaOrmService = new CategoriaOrmService(_databaseContext);
            var categorias = _categoriaOrmService.ObterCategorias();
            
            var _etiquetaOrmService = new EtiquetaOrmService(_databaseContext);
            var etiquetas = _etiquetaOrmService.ObterEtiqueta();
            
            foreach (var autor in autores)
            {
                var author = new AutorCreate();
                author.Id = autor.Id;
                author.Nome = autor.Nome;
                modal.Autor.Add(author);
            }

            foreach (var cat in categorias)
            {
                var category = new CategoriaCreate();
                category.Id = cat.Id;
                category.Nome = cat.Nome;
                foreach (var tag in cat.Etiquetas)
                {
                    var tagIndex = new EtiquetaIndex();
                    tagIndex.Categoria = tag.Categoria;
                    tagIndex.Id = tag.Id;
                    tagIndex.Nome = tag.Nome;
                    category.etiquetaIndex.Add(tagIndex);
                }
                
                modal.Categoria.Add(category);
            }

            foreach (var et in etiquetas)
            {
                var tag = new EtiquetaIndex();
                tag.Id = et.Id;
                tag.Nome = et.Nome;
                tag.Categoria = et.Categoria;
                modal.PostagensEtiqueta.Add(tag);
            }
            return View(modal);
        }
        
        [HttpPost]
        [Route("admin/postagem/create")]
        public IActionResult Create(AdminPostagemCriarRequestModel request)
        {
            var today = DateTime.Now;

            var postagem = new PostagemEntity();
            var categoriaId = request.listCategorias;
            var autorId = request.listAutores;
            var etiquetaId = request.listEtiquetas;

            var _autorOrmService = new AutorOrmService(_databaseContext);
            var _categoriaOrmService = new CategoriaOrmService(_databaseContext);
            var _etiquetaOrmService = new EtiquetaOrmService(_databaseContext);

            var categoria = _categoriaOrmService.ObterCategoriaPorId(categoriaId);
            var autor = _autorOrmService.ObterAutorPorId(autorId);
            var etiqueta = _etiquetaOrmService.ObterEtiquetaPorId(etiquetaId);
            postagem.Autor = autor;
            postagem.Categoria = categoria;
            postagem.Descricao = request.Descricao;
            postagem.Titulo = request.Titulo;
            postagem.Data = request.Data;
            postagem.Time = request.Hora;
            var date = String.Format("{0:yyyy-MM-dd}", today);
            var hora = String.Format("{0:HH:mm}", today);
            if (date == postagem.Data && hora==postagem.Time)
            {
                var model = new PostagemIndexViewModel();
                try
                {
                    _postagemOrmService.AddPostagem(postagem);
                    model.Message = "Criado com sucesso!!";
                    model.Tipo = "Criar";    
                }
                catch (Exception e)
                {
                    TempData["erro-msg"] = e.Message;
                    return RedirectToAction("Create");
                }

                return RedirectToAction("Index", new {message = model.Message, tipo = model.Tipo});
            }
            else
            {
                var doPost = Task.Run(()=>DoPost(postagem,_serviceScopeFactory));

                return RedirectToAction("Index");
            }
        }

        public async Task<IActionResult> DoPost(PostagemEntity postagem,IServiceScopeFactory serviceScopeFactory)
        {
            {
                var model = new PostagemIndexViewModel();
                while (model.Message == null)
                {
                    var today = DateTime.Now;
                    var date = string.Format("{0:yyyy-MM-dd}", today);
                    var hora = string.Format("{0:HH:mm}", today);
                    if (date == postagem.Data && hora == postagem.Time)
                    {
                        var scope = serviceScopeFactory.CreateScope();
                        scope.ServiceProvider.GetService<PostagemOrmService>().AddPostagem(postagem);
                        model.Message = "Salvo";
                    }
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        [Route("admin/postagem/edit/{id?}")]
        public IActionResult Edit(int id)
        {
            return View();
        }
        
        [HttpPost]
        [Route("admin/postagem/edit")]
        public IActionResult Update(AdminPostagemUpdateRequestModel request)
        {
            return RedirectToAction("Index");
        }
        
        [Route("admin/postagem/remove/{id?}")]
        public IActionResult Remove(int id)
        {
            return RedirectToAction("Index");
        }
        
        [Route("admin/postagem/details/{id?}")]
        public IActionResult Details(int id)
        {
            return View();
        }
        
        [Route("admin/postagem/listRevisoes/{id?}")]
        public IActionResult ListRevisao(int id)
        {
            return View();
        }
        
        [Route("admin/postagem/listEtiquetas/{id?}")]
        public IActionResult ListEtiqueta(int id)
        {
            return View();
        }


        [Route("admin/postagem/descricao/{id?}")]
        public IActionResult LoadDescricao(int id)
        {
            var postagem = _postagemOrmService.ObterPostagemPorId(id);
            var model = new PostagemLoadDescricaoViewModel();
            model.Descricao = postagem.Descricao;
            return View(model);
        }
    }
}

BLOG/PWABlog/Views/adminPostagem/Create.cshtml
@using PWABlog.ViewModels.Admin.postagem
@model PWABlog.ViewModels.Admin.postagem.PostagemCreateViewModel
@using(Html.BeginForm("Create","AdminPostagem",FormMethod.Post))
    {
        
        <div class="form-group">
            @Html.Label(null,"Titulo",new{@for="titulo"})
            @Html.EditorFor(model =>model.Titulo,new{htmlAttributes = new{@class="form-control",@type="Text",@id="titulo",@placeholder="Nome do Titulo"}} )
        </div>
        <div class="form-group">
            @Html.Label(null,"Descrição",new{@for="descricao"})
            @Html.EditorFor(model =>model.Descricao,new{htmlAttributes = new{@class="form-control",@type="Text",@id="descricao",@placeholder="Descricão"}} )
        </div>
        <div class="form-group">
            @Html.Label(null,"Data",new{@for="data"})
            @Html.EditorFor(model =>model.Data,new{htmlAttributes = new{@class="form-control",@type="date",@id="data"}} )
            @Html.Label(null,"Hora",new{@for="hora"})
            @Html.EditorFor(model =>model.Hora,new{htmlAttributes = new{@class="form-control",@type="time",@id="hora"}} )
        </div>
        @if(Model.Autor.Count != 0)
        {
            <div class="form-group">
                @Html.Label(null,"Autor",new{@for="autor"})
                <select class="form-control" name="listAutores"  id="autor">
                    @foreach (var autor in Model.Autor)
                    {
                        <option class="list-group-item" value="@autor.Id">@autor.Nome</option>
                    }
                </select>
            </div>
        }else{
            @Html.ActionLink("Novo Autor","Create","AdminAutor",null,new{@class="btn btn-primary",style="margin-left='2%';"})
        }
        @if (Model.Categoria.Count!=0)
        {
            <div class="form-group">
                @Html.Label(null,"Categoria",new{@for="categoria"})
                <select class="form-control" name="listCategorias" id="categoria">
                    @foreach (var categoria in Model.Categoria)
                    {
                        <option class="list-group-item" value="@categoria.Id">@categoria.Nome</option>
                    }
                </select>
            </div>
        }else{
            @Html.ActionLink("Nova Categoria","Create","AdminCategoria",null,new{@class="btn btn-primary"})
        }
        @if (Model.PostagensEtiqueta.Count != 0)
        {
            <div class="form-group">
                @Html.Label(null,"Etiqueta",new{@for="etiqueta"})
                <select class="form-control" name="listEtiquetas" id="etiqueta">
                    @foreach (var tag in Model.PostagensEtiqueta)
                    {
                        <option class="list-group-item" value="@tag.Id">@tag.Nome</option>
                    }
                </select>
            </div>
        }else{
            @Html.ActionLink("Nova Etiqueta","Create","AdminEtiqueta",null,new{@class="btn btn-primary"})
        }
        <div>
            <input type="submit" class="btn btn-primary" value="Gravar">
        </div>
    }


BLOG/PWABlog/Views/adminPostagem/Details.cshtml
@using PWABlog.ViewModels.Admin.Categoria
@model PWABlog.ViewModels.Admin.Categoria.CategoriaDetailsViewModel
<div class="form-group">
    @Html.Label(null,"Id",new{@for="idCategoria"})
    @Html.EditorFor(model =>model.Id,new{htmlAttributes = new{@class="form-control",@type="numeric",@id="idCategoria",@value = @Model.Id,@disabled=true}} )
</div>
<div class="form-group">
    @Html.Label(null,"Nome Categoria",new{@for="nomeCategoria"})
    @Html.EditorFor(model =>model.Nome,new{htmlAttributes = new{@class="form-control",@type="Text",@id="nomeCategoria",@value = @Model.Nome,@disabled=true}} )
</div>

<div>
    @Html.ActionLink("Voltar","Index","AdminCategoria",null,new{@class="btn btn-secondary"})
</div>

BLOG/PWABlog/Views/adminPostagem/Edit.cshtml
@using PWABlog.ViewModels.Admin.postagem
@model PWABlog.ViewModels.Admin.postagem.PostagemCreateViewModel


BLOG/PWABlog/Views/adminPostagem/Index.cshtml
@using PWABlog.ViewModels.Admin.postagem
@model PWABlog.ViewModels.Admin.postagem.PostagemIndexViewModel

<!-- Elaboração de uma mensagem correspodende ao tipo de ação realizado no controller-->

@if (Model.Tipo != null)
{
        @switch (Model.Tipo)
        {
            case "Criar":
                <div class="alert alert-primary" role="alert">
                    @Model.Message
                </div>
                break;
            case "Deletar":
                <div class="alert alert-danger" role="alert">
                    @Model.Message
                </div>
                break;
            case "Update":
                <div class="alert alert-primary" role="alert">
                     @Model.Message
                </div>
                break;
        }
}

<!-- Action link para adionar uma nova categoria  -->

@Html.ActionLink("Nova Postagem", "Create", "AdminPostagem", null, new { @class = "btn btn-primary" })

<!--Lista todas as categorias-->

<table class="table table-bordered ">
    <thead class="thead-dark">
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Titulo</th>
        <th scope="col">Descrição</th>
        <th scope="col">Autor</th>
        <th scope="col">Categoria</th>
        <th scope="col">Etiquetas</th>
        <th scope="col">Revisões</th>
        <th scope="col">Data e Hora</th>
        <th scope="col">Ações</th>
    </tr>
    </thead>
    <tbody>
    @foreach(var postagem in Model.Postagens)
    {
        <tr>
            <th>@postagem.Id</th>
            <th>@postagem.Titulo</th>
            <th>@Html.ActionLink("Descrição","LoadDescricao","AdminPostagem",new {id = postagem.Id},new{@class="btn btn-primary"})</th>
            <th>@postagem.Autor</th>
            <th>@postagem.Categoria</th>
            <th>@Html.ActionLink("Etiquetas","ListEtiqueta","AdminPostagem",null,new{@class="btn btn-primary"})</th>
            <th>@Html.ActionLink("Revisões","ListRevisao","AdminPostagem",null,new{@class="btn btn-primary"})</th>
            <th>@postagem.Data @postagem.Time</th>
                
            <th>
               <a class="btn" href=@Url.Action("Edit","AdminPostagem",new {id = postagem.Id})><i class="fa fa-pencil-square-o" aria-hidden="true"> Edit</i></a>|
                <a class="btn" href=@Url.Action("Remove","AdminPostagem",new {id = postagem.Id})><i class="fa fa-trash" aria-hidden="true"> Deletar</i></a>|
                <a class="btn" href=@Url.Action("Details","AdminPostagem",new {id = postagem.Id})><i class="fa fa-eye" aria-hidden="true"> View</i></a>
            </th>
        </tr>
    }
    </tbody>
</table>

BLOG/PWABlog/Views/adminPostagem/ListEtiqueta.cshtml
@using PWABlog.ViewModels.Admin.postagem
@model PWABlog.ViewModels.Admin.postagem.PostagemIndexViewModel
<h2>title</h2>

BLOG/PWABlog/Views/adminPostagem/ListRevisao.cshtml
@using PWABlog.ViewModels.Admin.postagem
@model PWABlog.ViewModels.Admin.postagem.PostagemIndexViewModel
<h2>title</h2>

BLOG/PWABlog/Views/adminPostagem/LoadDescricao.cshtml
@using PWABlog.ViewModels.Admin.postagem
@model PWABlog.ViewModels.Admin.postagem.PostagemLoadDescricaoViewModel

<div class="card w-50">
  <div class="card-body">
    <h5 class="card-title">Descrição</h5>
    <p class="card-text">@Model.Descricao</p>
    @Html.ActionLink("Voltar","Index","AdminPostagem",null,new{@class="btn btn-secondary"})
  </div>
</div>

