BLOG/PWABlog/Controllers/admin/AdminAutorController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using PWABlog.Models.Blog.Autor;
using PWABlog.RequestModels.autor;
using PWABlog.ViewModels.Admin.autor;
// ReSharper disable All

namespace PWABlog.Controllers.admin
{
    public class AdminAutorController : Controller
    {
        private readonly AutorOrmService _autorOrmService;

        public AdminAutorController(AutorOrmService autorOrmService)
        {
            _autorOrmService = autorOrmService;
        }
        
       [Route("admin/autor/index")]
       [Route("admin/autor")]
        public IActionResult Index()
        {
            var model = new AutorIndexViewModel();
            var autores = _autorOrmService.ObterAutores();

            foreach (var autor in autores)
            {
                var author = new AutorIndex();
                author.Id = autor.Id;
                author.Nome = autor.Nome;
                model.Autores.Add(author);
            }
            
            return View(model);
        }

        [HttpGet]
        [Route("admin/autor/create")]
        public IActionResult Create()
        {
            var model = new AutorCreateViewModel();
            model.Title = "Adicionar Autor";
            return View(model);
        }

        [HttpPost]
        [Route("admin/autor/create/{id?}")]
        public IActionResult Create(AdminAutorCriarRequestModel request)
        {
            var nome = request.Nome;
            var model = new AutorIndexViewModel();
            try
            {
                _autorOrmService.AddAutor(nome);
                model.Message = "Criado com sucesso!!";
                model.Tipo = "Criar";
            }
            catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Create");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
           
        }

        [Route("admin/autor/edit/{id?}")]
        public IActionResult Edit(int id)
        {
            var author = _autorOrmService.ObterAutorPorId(id);
            var model = new AutorEditViewModel();
            model.Id = author.Id;
            model.Nome = author.Nome;
            return View(model);
        }

        [HttpPost]
        public IActionResult Update(AdminAutorUpdateRequestModel request)
        {
            var nome = request.Nome;
            var id = request.Id;
            var model = new AutorIndexViewModel();
            try
            {
                var author = new AutorEntity{Id=id,Nome = nome};
                _autorOrmService.UpdateAutor(author);
                model.Message = "Atualizado com sucesso!!";
                model.Tipo = "Update";
            }
            catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Update");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        [Route("admin/autor/remove/{id?}")]
        public IActionResult Remove(AdminAutorDeleteRequestModel request)
        {
            var id = request.Id;
            var model = new AutorIndexViewModel();
            try
            {
                _autorOrmService.RemoveAutor(id);
                model.Message = "Deletado com sucesso!!";
                model.Tipo = "Deletar";
            }catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }

        [Route("admin/autor/view/{id?}")]
        public IActionResult Details(int id)
        {
            var model = new AutorDetailsViewModel();
            var categoria = _autorOrmService.ObterAutorPorId(id);
            model.Id = categoria.Id;
            model.Nome = categoria.Nome;
            return View(model);
        }
    }
}

BLOG/PWABlog/Controllers/admin/AdminController.cs
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using PWABlog.ViewModels.Admin.admin;

namespace PWABlog.Controllers.admin
{
    [Authorize]
    public class AdminController : Controller
    {
        private readonly DatabaseContext _databaseContext;
        public AdminController(DatabaseContext databaseContext)
        {
            _databaseContext = databaseContext;
        }
        
        [HttpGet]
        [Route("admin")]
        public IActionResult Index()
        {
            var model = new AdminViewModel();
            model.Author = _databaseContext.Autores.ToList().Count;
            model.Category = _databaseContext.Categorias.ToList().Count;
            model.Posts = _databaseContext.Postagens.ToList().Count;
            model.Tags = _databaseContext.Etiquetas.ToList().Count;
            return View(model);
        }
    }
}

BLOG/PWABlog/Controllers/admin/AdminEtiquetaController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using PWABlog.Models.Blog.Categoria;
using PWABlog.Models.Blog.Etiqueta;
using PWABlog.RequestModels.etiqueta;
using PWABlog.ViewModels.Admin.Categoria;
using PWABlog.ViewModels.Admin.etiqueta;

namespace PWABlog.Controllers.admin
{
    public class AdminEtiquetaController : Controller
    {
        private readonly EtiquetaOrmService _etiquetaOrmService;
        private readonly DatabaseContext _databaseContext;
        private readonly EtiquetaOrmService _categoriaOrmService;

        public AdminEtiquetaController(EtiquetaOrmService etiquetaOrmService,DatabaseContext databaseContext)
        {
            _etiquetaOrmService = etiquetaOrmService;
            _databaseContext = databaseContext;
        }

        /* Página inicial da etiqueta com suas rotas*/
        
        [Route("admin/etiqueta/index")]
        [Route("admin/etiqueta")]
        public IActionResult Index(string message,string tipo)
        {
            ViewBag.Title = "Lista de etiquetas";
            var model = new EtiquetaIndexViewModel();
            model.Message = message;
            model.Tipo = tipo;
            var etiquetas = _etiquetaOrmService.ObterEtiqueta();
            foreach (var tag in etiquetas)
            {
               var etiqueta = new ViewModels.Admin.etiqueta.EtiquetaIndex();
               etiqueta.Id = tag.Id;
               etiqueta.Nome = tag.Nome;
               etiqueta.Categoria = tag.Categoria;
               model.Etiquetas.Add(etiqueta);
            }
            return View(model);
        }
        
        /*Retorn a view Create para colocar os dados*/
        
        [HttpGet]
        [Route("admin/etiqueta/create")]
        public IActionResult Create()
        {
            ViewBag.title = "Adicionar Tag";
            var modal = new EtiquetaCreateViewModel();
            var _categoriaOrmService = new CategoriaOrmService(_databaseContext);
            var categorias = _categoriaOrmService.ObterCategorias();
            
            foreach (var cat in categorias)
            {
                var category = new EtiquetaCategoriaCreate();
                category.Id = cat.Id;
                category.Nome = cat.Nome;
                modal.Categoria.Add(category);
            }
            return View(modal);
        }
        
        /* Realiza a ação de insert no banco */
        
        [HttpPost]
        [Route("admin/etiqueta/create")]
        public IActionResult Create(AdminEtiquetaCriarRequestModel request)
        {
            var nome = request.Nome;
            var categoriaId = request.ListCategorias;
            var _categoriaOrmService = new CategoriaOrmService(_databaseContext);
            var categoria = _categoriaOrmService.ObterCategoriaPorId(categoriaId);
            var model = new EtiquetaIndexViewModel();
            try
            {
                _etiquetaOrmService.AddEtiqueta(nome,categoria);
                model.Message = "Criado com sucesso!!";
                model.Tipo = "Criar";
            }
            catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Create");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        /* Edita os dados , nome, da etiqueta */
        
        [HttpGet]
        [Route("admin/etiqueta/edit")]
        public IActionResult Edit(int id)
        {
            ViewBag.title = "Update tag";
            var etiqueta = _etiquetaOrmService.ObterEtiquetaPorId(id);
            var model = new EtiquetaEditViewModel();
            model.Id = etiqueta.Id;
            model.Nome = etiqueta.Nome;
            return View(model);
        }
        
        /* Realiza o update dos dados*/
        
        [HttpPost]
        [Route("admin/etiqueta/edit")]
        public IActionResult Update(AdminEtiquetaUpdateRequestModel request)
        {
            var nome = request.Nome;
            var id = request.Id;
            var model = new EtiquetaIndexViewModel();
            try
            {
                var tag = new EtiquetaEntity{Id=id,Nome = nome};
                _etiquetaOrmService.UpdateEtiqueta(tag);
                model.Message = "Atualizado com sucesso!!";
                model.Tipo = "Update";
            }
            catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Update");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        /* Realiza a removção dos dados no banco e na aplicação */
        
        [Route("admin/etiqueta/remove/{id}")]
        public IActionResult Remove(AdminEtiquetaDeleteRequestModel request)
        {
            var id = request.Id;
            var model = new CategoriaIndexViewModel();
            try
            {
                _etiquetaOrmService.RemoveEtiqueta(id);
                model.Message = "Deletado com sucesso!!";
                model.Tipo = "Deletar";
            }catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        /* Visualização de todos os detalhes */
        
        [Route("admin/etiqueta/view/{id?}")]
        public IActionResult Details(int id)
        {
            ViewBag.title = "Details tag";
            var model = new EtiquetaDetailsViewModel();
            var tag = _etiquetaOrmService.ObterEtiquetaPorId(id);
            model.Id = tag.Id;
            model.Nome = tag.Nome;
            return View(model);
        }
    }
}

BLOG/PWABlog/Controllers/admin/ControlAcessController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using PWABlog.Models.AcessControl;
using PWABlog.ViewModels.ControlAcess;

namespace PWABlog.Controllers.admin
{
    public class ControlAcessController : Controller
    {
        private readonly ControlAcessService _controlAcessService;

        public ControlAcessController(ControlAcessService controlAcessService)
        {
            _controlAcessService = controlAcessService;
        }
        [Route("")]
        [Route("login")]
        public IActionResult Login()
        {
            var model = new ControlAcessLoginViewModel();
            model.RegisterMenssage = (string) TempData["msg-register"];
            model.LoginMenssage = (string) TempData["msg-login"];
            return View(model);
        }

        [HttpPost]
        [Route("/login")]
        public async Task<RedirectResult> Login(ControlAcessLoginRequestModel request)
        {
            var user = request.Email;
            var password = request.Password;
            if (user == null)
            {
                TempData["msg-login"] = "Please enter with username";
                RedirectToAction("Login");
            }

            if (password == null)
            {
                TempData["msg-login"] = "Please enter with password";
                RedirectToAction("Login");
            }

            try
            {
                await _controlAcessService.AuthenticationUser(user, password);
                return Redirect("/Home");
            }
            catch (Exception e)
            {
                TempData["msg-login"] = e.Message;
                return Redirect("Login");
            }
        }

        public IActionResult Logout()
        {
            _controlAcessService.LogoutUser();
            return RedirectToAction("Login");
        }

        [HttpGet]
        [Route("/register")]
        public IActionResult Register()
        {
            var model = new ControlAcessRegisterViewModel();
            //model.RegisterError = (string) TempData["register-error"];
            model.Error = (string) TempData["msg-error"];
            return View(model);
        }

        [HttpPost]
        [Route("/register/add")]
        public async Task<RedirectToActionResult> RegisterPost(ControlAcessRegisterRequestModel request)
        {
            var email = request.Email;
            var password = request.Password;
            var token = request.Token;
            var nickName = request.NickName;

            if (email == null)
            {
                TempData["msg-error"] = "Please, enter with email";
                return RedirectToAction("Register");
            }
            if (password == null)
            {
                TempData["msg-error"] = "Please, enter with password";
                return RedirectToAction("Register");
            }
            if (nickName == null)
            {
                TempData["msg-error"] = "Please, enter with nickname";
                return RedirectToAction("Register");
            }
            if (!token.Equals("BLOG-PWA-2020"))
            {
                TempData["msg-error"] = "Token disabled";
                return RedirectToAction("Register");
                
            }

            try
            {
                await _controlAcessService.RegisterUser(email, password, nickName);
                TempData["msg-register"] = "Registered user";
                return RedirectToAction("Login");
            }
            catch (RegisterUserExeception e)
            {
                var ListError = new List<string>();

                foreach (var error in e.Error)
                {
                    ListError.Add(error.Description);
                }

                TempData["register-error"] = ListError;
                return RedirectToAction("Register");
            }

            return null;
        }
    }
}

BLOG/PWABlog/Views/Shared/_Layout.cshtml
@using PWABlog.Models.Blog.Etiqueta
<!DOCTYPE html>
<html lang="pt-BR">
<title>@Model.TitlePage</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="~/theme/w3schools-blog-theme.css">
<link rel="stylesheet" href="~/theme/core.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="~/vendor/font-awesome-4.7.0/css/font-awesome.css" />

<body class="w3-light-grey">
<!-- w3-content defines a container for fixed size centered content, 
and is wrapped around the whole page content, except for the footer in this example -->
    <div class="w3-content" style="max-width:1400px">

        <!--NavBar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                @Html.ActionLink("Home","index","Home",null,new { @class="navbar-brand"})
                <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                    <li class="nav-item">
                        @Html.ActionLink("Autor", "Index", "AdminAutor",null,new { @class = "nav-link"})
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Categoria", "Index", "adminCategoria",null,new { @class = "nav-link"})
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Etiqueta", "Index", "AdminEtiqueta",null,new { @class = "nav-link"})
                    </li>
                    <li class="nav-item">
                        @Html.ActionLink("Postagem", "Index", "AdminPostagem",null,new { @class = "nav-link"})
                    </li>
                    <li>
                        @Html.ActionLink("Painel","Index","Admin",null,new{@class="nav-link"})
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
        </nav>



        <!-- Header -->
        <header class="w3-container w3-center w3-padding-32">
            <h1>
                <b>MY BLOG</b>
            </h1>
            <div>
                <span>Welcome to the blog @User.Identity.Name</span>
                @Html.ActionLink("Logout","Logout","ControlAcess",null,new{@class="btn  btn-danger"})
            </div>
        </header>

        <!-- Grid -->
        <div class="w3-row">

            @RenderBody()


            <!-- END GRID -->
        </div><br>

        <!-- END w3-content -->
    </div>

<!-- Footer -->
<footer class="w3-container w3-dark-grey w3-padding-32 w3-margin-top">
    <button class="w3-button w3-black w3-disabled w3-padding-large w3-margin-bottom">Previous</button>
    <button class="w3-button w3-black w3-padding-large w3-margin-bottom">Next »</button>
    <p>Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
</footer>

</body>
</html>

BLOG/PWABlog/Views/Shared/_LayoutCommon.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@Model.TitlePage</title>
</head>
<body>
<h1>Usuário</h1>
@User.Identity.Name
@Html.ActionLink("Logout","Logout","ControlAcess",new{@class="btn btn-primary"})
@RenderBody()
</body>
</html>

BLOG/PWABlog/Views/Shared/_LayoutControlAcess.cshtml
@using PWABlog.ViewModels.ControlAcess
<!DOCTYPE html>
<html lang="pt-BR">
<title>@Model.TitlePage</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">
<link rel="stylesheet" href="~/theme/w3schools-blog-theme.css">
<link rel="stylesheet" href="~/theme/core.css">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
<link rel="stylesheet" href="~/vendor/font-awesome-4.7.0/css/font-awesome.css" />

<body class="w3-light-grey">
@RenderBody()
</body>
</html>