BLOG/PWABlog/Controllers/admin/AdminCategoriaController.cs
using System;
using System.Collections.Generic;
using System.Security.Permissions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Routing;
using PWABlog.Models.Blog.Categoria;
using PWABlog.RequestModels;
using PWABlog.ViewModels.Admin.Categoria;

namespace PWABlog.Controllers.admin
{
    public class AdminCategoriaController : Controller
    {
        /* Instacia as ações em que as actions realizarão no banco */
        
        private readonly CategoriaOrmService _categoriaOrmService;

        public AdminCategoriaController(CategoriaOrmService categoriaOrmService)
        {
            _categoriaOrmService = categoriaOrmService;
        }

        /* Página inicial da categoria com suas rotas*/
        
        [Route("admin/categoria/index")]
        [Route("admin/categoria")]
        public IActionResult Index(string message,string tipo)
        {
            ViewBag.Title = "Index";
            var model = new CategoriaIndexViewModel();
            model.Message = message;
            model.Tipo = tipo;
            var categorias = _categoriaOrmService.ObterCategorias();
            foreach (var categoria in categorias)
            {
                var categoriaIndex = new CategoriaIndex();
                categoriaIndex.CategoriaId = categoria.Id;
                categoriaIndex.Nome = categoria.Nome;
                model.Categorias.Add(categoriaIndex);
            }
            return View(model);
        }
        
        /*Retorn a view Create para colocar os dados*/
        
        [HttpGet]
        [Route("admin/categoria/create")]
        public IActionResult Create()
        {
            return View();
        }
        
        /* Realiza a ação de insert no banco */
        
        [HttpPost]
        [Route("admin/categoria/create")]
        public IActionResult Create(AdminCategoriaCriarRequestModel request)
        {
            var nome = request.Nome;
            var model = new CategoriaIndexViewModel();
            try
            {
                _categoriaOrmService.AddCategoria(nome);
                model.Message = "Criado com sucesso!!";
                model.Tipo = "Criar";
            }
            catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Create");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        /* Edita os dados , nome, da categoria*/
        
        [HttpGet]
        [Route("admin/categoria/edit")]
        public IActionResult Edit(int id)
        {
            var categoria = _categoriaOrmService.ObterCategoriaPorId(id);
            var model = new CategoriaEditViewModel();
            model.Etiquetas = categoria.Etiquetas;
            model.Postagens = categoria.Postagens;
            model.Id = categoria.Id;
            model.Nome = categoria.Nome;
            return View(model);
        }
        
        /* Realiza o update dos dados*/
        
        [HttpPost]
        [Route("admin/categoria/edit")]
        public IActionResult Update(AdminCategoriaUpdateRequestModel request)
        {
            var nome = request.Nome;
            var id = request.Id;
            var model = new CategoriaIndexViewModel();
            try
            {
                var categoria = new CategoriaEntity{Id=id,Nome = nome};
                _categoriaOrmService.UpdateCategoria(categoria);
                model.Message = "Atualizado com sucesso!!";
                model.Tipo = "Update";
            }
            catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Update");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        /* Realiza a removção dos dados no banco e na aplicação*/
        
        [Route("admin/categoria/remove/{id}")]
        public IActionResult Remove(AdminCategoriaDeletarRequestModel request)
        {
            var id = request.Id;
            var model = new CategoriaIndexViewModel();
            try
            {
                _categoriaOrmService.removeCategoria(id);
                model.Message = "Deletado com sucesso!!";
                model.Tipo = "Deletar";
            }catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        /* Visualização de todos os detalhes */
        
        [Route("admin/categoria/view/{id?}")]
        public IActionResult Details(int id)
        {
            var model = new CategoriaDetailsViewModel();
            var categoria = _categoriaOrmService.ObterCategoriaPorId(id);
            model.Id = categoria.Id;
            model.Nome = categoria.Nome;
            return View(model);
        }
    }
}

BLOG/PWABlog/Controllers/admin/AdminEtiquetaController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using PWABlog.Models.Blog.Categoria;
using PWABlog.Models.Blog.Etiqueta;
using PWABlog.RequestModels.etiqueta;
using PWABlog.ViewModels.Admin.Categoria;
using PWABlog.ViewModels.Admin.etiqueta;

namespace PWABlog.Controllers.admin
{
    public class AdminEtiquetaController : Controller
    {
        private readonly EtiquetaOrmService _etiquetaOrmService;
        private readonly DatabaseContext _databaseContext;
        private readonly EtiquetaOrmService _categoriaOrmService;

        public AdminEtiquetaController(EtiquetaOrmService etiquetaOrmService,DatabaseContext databaseContext)
        {
            _etiquetaOrmService = etiquetaOrmService;
            _databaseContext = databaseContext;
        }

        /* Página inicial da etiqueta com suas rotas*/
        
        [Route("admin/etiqueta/index")]
        [Route("admin/etiqueta")]
        public IActionResult Index(string message,string tipo)
        {
            ViewBag.Title = "Lista de etiquetas";
            var model = new EtiquetaIndexViewModel();
            model.Message = message;
            model.Tipo = tipo;
            var etiquetas = _etiquetaOrmService.ObterEtiqueta();
            foreach (var tag in etiquetas)
            {
               var etiqueta = new ViewModels.Admin.etiqueta.EtiquetaIndex();
               etiqueta.Id = tag.Id;
               etiqueta.Nome = tag.Nome;
               etiqueta.Categoria = tag.Categoria;
               model.Etiquetas.Add(etiqueta);
            }
            return View(model);
        }
        
        /*Retorn a view Create para colocar os dados*/
        
        [HttpGet]
        [Route("admin/etiqueta/create")]
        public IActionResult Create()
        {
            ViewBag.title = "Adicionar Tag";
            var modal = new EtiquetaCreateViewModel();
            var _categoriaOrmService = new CategoriaOrmService(_databaseContext);
            var categorias = _categoriaOrmService.ObterCategorias();
            
            foreach (var cat in categorias)
            {
                var category = new EtiquetaCategoriaCreate();
                category.Id = cat.Id;
                category.Nome = cat.Nome;
                modal.Categoria.Add(category);
            }
            return View(modal);
        }
        
        /* Realiza a ação de insert no banco */
        
        [HttpPost]
        [Route("admin/etiqueta/create")]
        public IActionResult Create(AdminEtiquetaCriarRequestModel request)
        {
            var nome = request.Nome;
            var categoriaId = request.ListCategorias;
            var _categoriaOrmService = new CategoriaOrmService(_databaseContext);
            var categoria = _categoriaOrmService.ObterCategoriaPorId(categoriaId);
            var model = new EtiquetaIndexViewModel();
            try
            {
                _etiquetaOrmService.AddEtiqueta(nome,categoria);
                model.Message = "Criado com sucesso!!";
                model.Tipo = "Criar";
            }
            catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Create");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        /* Edita os dados , nome, da etiqueta */
        
        [HttpGet]
        [Route("admin/etiqueta/edit")]
        public IActionResult Edit(int id)
        {
            ViewBag.title = "Update tag";
            var etiqueta = _etiquetaOrmService.ObterEtiquetaPorId(id);
            var model = new EtiquetaEditViewModel();
            model.Id = etiqueta.Id;
            model.Nome = etiqueta.Nome;
            return View(model);
        }
        
        /* Realiza o update dos dados*/
        
        [HttpPost]
        [Route("admin/etiqueta/edit")]
        public IActionResult Update(AdminEtiquetaUpdateRequestModel request)
        {
            var nome = request.Nome;
            var id = request.Id;
            var model = new EtiquetaIndexViewModel();
            try
            {
                var tag = new EtiquetaEntity{Id=id,Nome = nome};
                _etiquetaOrmService.UpdateEtiqueta(tag);
                model.Message = "Atualizado com sucesso!!";
                model.Tipo = "Update";
            }
            catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Update");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        /* Realiza a removção dos dados no banco e na aplicação */
        
        [Route("admin/etiqueta/remove/{id}")]
        public IActionResult Remove(AdminEtiquetaDeleteRequestModel request)
        {
            var id = request.Id;
            var model = new CategoriaIndexViewModel();
            try
            {
                _etiquetaOrmService.RemoveEtiqueta(id);
                model.Message = "Deletado com sucesso!!";
                model.Tipo = "Deletar";
            }catch(Exception e)
            {
                TempData["erro-msg"] = e.Message;
                return RedirectToAction("Index");
            }
            return RedirectToAction("Index",new{message = model.Message,tipo = model.Tipo});
        }
        
        /* Visualização de todos os detalhes */
        
        [Route("admin/etiqueta/view/{id?}")]
        public IActionResult Details(int id)
        {
            ViewBag.title = "Details tag";
            var model = new EtiquetaDetailsViewModel();
            var tag = _etiquetaOrmService.ObterEtiquetaPorId(id);
            model.Id = tag.Id;
            model.Nome = tag.Nome;
            return View(model);
        }
    }
}

BLOG/PWABlog/Views/adminEtiqueta/Create.cshtml
@using PWABlog.ViewModels.Admin.etiqueta
@model PWABlog.ViewModels.Admin.etiqueta.EtiquetaCreateViewModel

@using(Html.BeginForm("Create","AdminEtiqueta",FormMethod.Post))
    {
        <div class="form-group">
            @Html.Label(null,"Nome Tag",new{@for="nomeEtiqueta"})
            @Html.EditorFor(model =>model.Nome,new{htmlAttributes = new{@class="form-control",@type="Text",@id="nomeEtiqueta",@placeholder="Nome"}} )
        </div>
        @if (Model.Categoria.Count!=0)
        {
            <div class="form-group">
                @Html.Label(null,"Categoria",new{@for="categoria"})
                <select class="form-control" name="listCategorias" id="categoria">
                    @foreach (var categoria in Model.Categoria)
                    {
                        <option class="list-group-item" value="@categoria.Id">@categoria.Nome</option>
                    }
                </select>
            </div>
           
        }else{
            <div class="form-group">
                 @Html.ActionLink("Nova Categoria","Create","AdminCategoria",null,new{@class="btn btn-primary"})
            </div>
        }
        <div>
            <input type="submit" class="btn btn-primary" value="Gravar">
        </div>
    }

BLOG/PWABlog/Views/adminEtiqueta/Details.cshtml
@using PWABlog.ViewModels.Admin.etiqueta
@model PWABlog.ViewModels.Admin.etiqueta.EtiquetaDetailsViewModel
<div class="form-group">
    @Html.Label(null,"Id",new{@for="idEtiqueta"})
    @Html.EditorFor(model =>model.Id,new{htmlAttributes = new{@class="form-control",@type="numeric",@id="idEtiqueta",@value = @Model.Id,@disabled=true}} )
</div>
<div class="form-group">
    @Html.Label(null,"Nome",new{@for="nomeEtiqueta"})
    @Html.EditorFor(model =>model.Nome,new{htmlAttributes = new{@class="form-control",@type="Text",@id="nomeEtiqueta",@value = @Model.Nome,@disabled=true}} )
</div>

<div>
    @Html.ActionLink("Voltar","Index","AdminCategoria",null,new{@class="btn btn-secondary"})
</div>

BLOG/PWABlog/Views/adminEtiqueta/Edit.cshtml
@using PWABlog.ViewModels.Admin.etiqueta
@model PWABlog.ViewModels.Admin.etiqueta.EtiquetaEditViewModel
@using(Html.BeginForm("Update","AdminCategoria",FormMethod.Post))
    {
        <div class="form-group">
            @Html.Label(null,"Id",new{@for="idEtiqueta"})
            @Html.EditorFor(model =>model.Id,new{htmlAttributes = new{@class="form-control",@type="numeric",@id="idEtiqueta",@value = @Model.Id,@disabled=true}} )
        </div>
        <div class="form-group">
            @Html.Label(null,"Nome",new{@for="nomeEtiqueta"})
            @Html.EditorFor(model =>model.Nome,new{htmlAttributes = new{@class="form-control",@type="Text",@id="nomeEtiqueta",@value = @Model.Nome}} )
        </div>
        <div>
            <input type="submit" class="btn btn-primary" value="Gravar">
        </div>
    }

BLOG/PWABlog/Views/adminEtiqueta/Index.cshtml
@using PWABlog.ViewModels.Admin.etiqueta
@model PWABlog.ViewModels.Admin.etiqueta.EtiquetaIndexViewModel

<!-- Elaboração de uma mensagem correspodende ao tipo de ação realizado no controller-->

@if (Model.Tipo != null)
{
        @switch (Model.Tipo)
        {
            case "Criar":
                <div class="alert alert-primary" role="alert">
                    @Model.Message
                </div>
                break;
            case "Deletar":
                <div class="alert alert-danger" role="alert">
                    @Model.Message
                </div>
                break;
            case "Update":
                <div class="alert alert-primary" role="alert">
                     @Model.Message
                </div>
                break;
        }
}

<!-- Action link para adionar uma nova tag  -->

@Html.ActionLink("Nova Tag", "Create", "AdminEtiqueta", null, new { @class = "btn btn-primary" })

<!--Lista todas as etiquetas-->

<table class="table table-bordered ">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Nome</th>
            <th scope="col">Categoria</th>
            <th scope="col">Ações</th>
        </tr>
    </thead>
    <tbody>
        @foreach(EtiquetaIndex tag in Model.Etiquetas)
        {
            <tr>
                <th>@tag.Id</th>
                <th>@tag.Nome</th>
                <th>@tag.Categoria.Nome</th>
                
                <th>
                    <a class="btn" href=@Url.Action("Edit","AdminEtiqueta",new {id = tag.Id})><i class="fa fa-pencil-square-o" aria-hidden="true"> Edit</i></a>|
                    <a class="btn" href=@Url.Action("Remove","AdminEtiqueta",new {id = tag.Id})><i class="fa fa-trash" aria-hidden="true"> Deletar</i></a>|
                    <a class="btn" href=@Url.Action("Details","AdminEtiqueta",new {id = tag.Id})><i class="fa fa-eye" aria-hidden="true"> View</i></a>
                </th>
            </tr>
        }
    </tbody>
</table>
